### ISSUE TITLE
Error upgrading past v4.0.3 - eslint-plugin-github should be dependency

### ISSUE THREAD

**Issue by chadfawcett** [primer/eslint-plugin-primer-react#165]
Hello! Attempting to update past v4.0.3 results in an error when we run our linter saying `eslint-plugin-github` couldn't be found. It also points to `primer-react/recommended` as the spot that's referencing it. 

It looks like `eslint-plugin-github` used to be a `dependency` AND a `devDependency`, but was removed from the `dependencies` in https://github.com/primer/eslint-plugin-primer-react/pull/106.

Since you are using `eslint-plugin-github` [in the published primer plugin](https://github.com/primer/eslint-plugin-primer-react/blob/15cfbb4a261c44418404249cc33e279bce25b2b7/src/configs/recommended.js#L10), I think it should be a `dependency` and not a `devDependency`.

I'm not familiar with the codebase though, so there may be a better explanation. Another option might be to make it a `peerDependency`.

**Comment by joshblack** [comment]
Hey @chadfawcett! Thanks so much for bringing this up, totally agreed too. Not sure how this got removed but it should definitely be a dependency or peerDependency 👍 

I'll ask the team to see which one we prefer and respond to the PR that you have open 👀 Thanks again for bringing this up!
