### ISSUE TITLE
Error running ESLint due to conflict with `eslint-plugin-primer-react` and `primer/primitives`

### ISSUE THREAD

**Issue by khiga8** [primer/eslint-plugin-primer-react#168]
Hi! The latest major version of `primer/primitives`, 8.1.0, appears to remove the deprecated colors folder which this library relies on. As a result, when a project is on the latest version of primer/primitives and we try to run ESLint, we run into:

```
Oops! Something went wrong! :(

ESLint: 8.57.0

Error: Failed to load plugin 'primer-react' declared in '--config': Cannot find module '@primer/primitives/dist/deprecated/colors'
Require stack:
- /home/runner/work/code-stats-collector/code-stats-collector/node_modules/eslint-plugin-primer-react/src/rules/no-deprecated-colors.js
- /home/runner/work/code-stats-collector/code-stats-collector/node_modules/eslint-plugin-primer-react/src/index.js
- /home/runner/work/code-stats-collector/code-stats-collector/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

```

Wanted to flag to see if you have a recommendation forward.

It looks like this surfaced as a conflict in - https://github.com/primer/eslint-plugin-primer-react/pull/167.

**Comment by broccolinisoup** [comment]
Hello @khiga8 👋 Thanks for raising this issue! I flagged it in our internal channel, hopefully we will resolve it soon. Apologies for the inconveniences in the meantime 😞

**Comment by joshblack** [comment]
@langermank do you want to be assigned to this because of your PR that will fix this? 👀

**Comment by khiga8** [comment]
This has been fixed, thanks to @langermank PR! :) https://github.com/primer/eslint-plugin-primer-react/pull/174
