### ISSUE TITLE
Create a lint rule that restricts tag usage

### ISSUE THREAD

**Issue by khiga8** [primer/eslint-plugin-primer-react#33]
Some components allow a `as` prop to be set. This flexibility can lead to non-semantic component usage which is very detrimental to accessibility.

For example, a `<Heading>` component should only ever render with a heading tag. However, it can currently be rendered with any tag like `<p>`.

Until a system-level update is made to define an allowlist for each component that accepts `prop`, we should restrict `as` values  with a lint rule.

If we can make a system-level change, that would be preferable, but I'm not sure what work is involved for that.

[Related Slack convo GitHub staff-only](https://github.slack.com/archives/C01L618AEP9/p1658271295944979)

**Comment by lesliecdubs** [comment]
We landed on decided to do a runtime check here: https://github.com/github/accessibility/issues/1504#issuecomment-1201546810. @inkblotty is this something the accessibility team was planning to pick up?

**Comment by inkblotty** [comment]
Yes, @lesliecdubs we have it planned for the Button component in Sprint 3 (starting Aug 15). We should expect to adjust other components at a later time.

**Comment by khiga8** [comment]
I will close this issue when this issue is resolved by the sprint 3 work :)

**Comment by lesliecdubs** [comment]
Awesome, thank you - great idea to add this lint rule! 

@khiga8 I'm going to assign you on this issue so you can close out when done 👍🏻

**Comment by khiga8** [comment]
I think @kendallgassner worked on this from a different angle in https://github.com/github/accessibility/issues/1504.
